# This is a basic workflow to help you get started with Actions
# all scripts are baased on the testing scripts for MagPiDownloader by @rubemlrm

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download Issues With end limit
        id: normalIssuesWithLimit
        shell: pwsh
        run: ./helloworld-downloader.ps1 -l 3
      - name: Download Issues with start and end limit
        id: normalIssuesWithRange
        shell: pwsh
        run: ./helloworld-downloader.ps1 -f 11 -l 12
      - name: lsah
        id: lslah
        shell: pwsh
        run: Get-ChildItem issues/
        # https://github.com/marketplace/actions/file-existence
      - name: "Check file existence"
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "issues/hello-world-issue-3.pdf, hello-world-issue-11.pd"
          allow_failure: false
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
  bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download Issues with end limit
        id: normalIssuesWithLimit
        run: bash ./helloworld-downloader.sh -l 3 && [[ -f issues/HelloWorld01.pdf ]]
      - name: Download Issues with start and end limit
        id: normalIssuesWithRange
        run: bash ./helloworld-downloader.sh -f 11 -l 12 && [[ -f issues/HW_12_Digital_Edition3.pdf ]]
  bash-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download Issues with end limit
        id: normalIssuesWithLimit
        run: bash ./helloworld-downloader.sh -l 3 && [[ -f issues/HelloWorld01.pdf ]]
      - name: Download Issues with start and end limit
        id: normalIssuesWithRange
        run: bash ./helloworld-downloader.sh -f 11 -l 12 && [[ -f issues/HW_12_Digital_Edition3.pdf ]]
